version: '3.9'

services:
  app:
    container_name: tokusatsu_back
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.docker
    networks:
      - tokusatsu
    restart: always

networks:
  tokusatsu:
    external: true
